ftc_compute_ingreso_laboral <- function(tbl) {
  tbl %>%
  dplyr::mutate(
    ingreso_laboral = INGRESO_ASALARIADO +
      COMISIONES +
      PROPINAS +
      HORAS_EXTRA +
      OTROS_PAGOS +
      BONO_VACACIONES +
      BONIFICACIONES +
      REGALIA_PASCUAL +
      INCENTIVO_ANTIGUEDAD +
      OTROS_BENEFICIOS +
      ESPECIE_ALIMENTOS +
      ESPECIE_VIVIENDA +
      ESPECIE_TRANSPORTE +
      ESPECIE_COMBUSTIBLE +
      ESPECIE_CELULAR +
      OTROS_ESPECIE +
      INGRESO_INDEPENDIENTES +
      CONSUMO_BIENES +
      ESPECIE_INDEPENDIENTES +
      INGRESO_ASALARIADO_SECUN +
      OTROS_PAGOS_SECUN +
      OTROS_BENEFICIOS_SECUN +
      PAGO_ESPECIE_SECUN +
      INGRESO_INDEPENDIENTES_SECUN +
      CONSUMO_BIENES_SECUN +
      ESPECIE_INDEPENDIENTES_SECUN +
      OTROS_TRABAJOS
  )
}
